/*
 * This source file was generated by the Gradle 'init' task
 */
package org.groovy.runner

class Main {
    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            try {
            } catch (t: Throwable) {
                t.printStackTrace()
            }
        }
    }
}
